namespace Vivarium.Biology;

public enum SensorType
{
    LocationX,
    LocationY,
    Random,
    Energy,
    Hunger,
    Age,
    Oscillator,
    AgentDensity,
    PlantDensity,
    StructureDensity,
    // 8-way directional densities (N, NE, E, SE, S, SW, W, NW)
    AgentDensity_N,
    AgentDensity_NE,
    AgentDensity_E,
    AgentDensity_SE,
    AgentDensity_S,
    AgentDensity_SW,
    AgentDensity_W,
    AgentDensity_NW,
    PlantDensity_N,
    PlantDensity_NE,
    PlantDensity_E,
    PlantDensity_SE,
    PlantDensity_S,
    PlantDensity_SW,
    PlantDensity_W,
    PlantDensity_NW,
    StructureDensity_N,
    StructureDensity_NE,
    StructureDensity_E,
    StructureDensity_SE,
    StructureDensity_S,
    StructureDensity_SW,
    StructureDensity_W,
    StructureDensity_NW,
    // Trait sensors (derived from genome)
    Strength,
    Bravery,
    MetabolicEfficiency,
    Perception,
    Speed,
    TrophicBias,
    Constitution,
}